ExpKeys.subject = "M487";
ExpKeys.DOB = "2023-08-29";
ExpKeys.species =  "mouse";
ExpKeys.genetics = "Ai-32";
ExpKeys.sex = "Male";
ExpKeys.probeDepth = 4.47; % in mm
ExpKeys.experimenter = "Manish";
ExpKeys.hemisphere =  "Right";
ExpKeys.date = "2024-02-03"; 
ExpKeys.insertion_AP = -2.8; % in mm, relative to bregma, posterior is minus
ExpKeys.insertion_ML = -3.2; % in mm, relative to bregma, left is plus, right is minus
ExpKeys.insertion_pitch = 90; % pinpoint convention
ExpKeys.insertion_yaw = 0; % pinpoint convention
ExpKeys.insertion_roll = 38; % pinpoint convention
ExpKeys.odor1_channel = "XA0";
ExpKeys.odor2_channel = "XA1";
ExpKeys.odor3_channel = "XA3";
ExpKeys.odor4_channel = "XA4";
ExpKeys.odor5_channel = "XA5";
ExpKeys.neutral_odor_channel = "XA2";
ExpKeys.odor1 = "0.04% benzaldehyde";
ExpKeys.odor2 = "0.08% ethyl butyrate";
ExpKeys.odor3 = "0.04% cinnamaldehyde";
ExpKeys.odor4 = "0.04% isobutyric acid";
ExpKeys.odor5 = "0.02% 2-heptanone";
ExpKeys.notes = "Random odors (1s on, 1s off), alternating with neutral";

